

GET http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/products/?category=living-area&limit=20&offset=0&size=&min_price=4000&max_price=5000
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==


###

POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/cart/add-to-cart/1/ 
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "user_id":16,
    "quantity":3,
    "variation_id":2
}

###

DELETE http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/cart/remove/68/ 
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "user_id":15
}

###
PUT http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/update_quantity/
Content-Type: application/json
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==

{
   
    "cart_item_id":69,
    "user_id":15,
        "quantity":1
}


### 
POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/add-to-wishlist/22/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "user_id":16
}

###

DELETE http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/remove-wishlist-item/52/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "user_id":15
}


###
DELETE http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/remove-selected-wishlist-items/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "user_id":15,
     "items":[40,41]

}

###
GET http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/rating/
Content-Type: application/json
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==


{
    "product_id" : 1
}

###
POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/ratingvalue
Content-Type: application/json
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==

{
    "rating": 4,
    "review": "Nice product!",
    "product_id": 1,
    "user_id":15
}

###
GET http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/rating/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{"product_id" : 4}


###
GET http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/profile/15/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json



###
PUT http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/profile/16/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "first_name": "",
    "last_name": "",
    "email":"",
    "phone": "+91 9080371821",
    "old_password":"Amvm1205$",
    "new_password":"Arun@1205"
}

###
POST  http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/orders/5/cancel/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "reason":"wrong order",
    "comments" : "I have mistakenly ordered the product"
}

###
POST https://countriesnow.space/api/v0.1/countries/states
Content-Type: application/json

{
    "country": "Nigeria"
}

###
GET  http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/order/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

 {"user_id" : 16}

###
POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/address/19/
Authorization: Basic ZGVrbzpkZWtvMTIzQDEyMw==
Content-Type: application/json

 {
        "first_name": "Arunmozhivarman",
        "address_1": "10/22a kamarajar street",
        "city": "Pollachi",
        "postcode": "642114",
        "Country_Region": "india",
        "email" : "arun@zinavo.in",
        "state_country": "tamilnadu",
        "phone": "+91 9080372821",
        "user":19
}

###
PUT http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/addresses/6/
Authorization: Basic ZGVrbzpkZWtvMTIzQDEyMw==
Content-Type: application/json

 {
        "first_name": "Arun M",
        "email": "arunakil12@gmail.com",
        "address_1": "okka412",
        "city": "kadapa",
        "postcode": "656879",
        "Country_Region": "india",
        "state_country": "andhra pradesh",
        "phone": "998877665246",
        "user":16
}


###
POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/order/
Authorization: Basic ZGVrbzpkZWtvMTIzQDEyMw==
Content-Type: application/json

 {
        "first_name": "Arunmozhivarman",
        "address_1": "10/22a kamarajar street",
        "city": "Pollachi",
        "postcode": "642114",
        "Country_Region": "india",
        "email" : "arun@zinavo.in",
        "state_country": "tamilnadu",
        "phone": "+91 9080372821",
        "user":19
}

###
POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/apply-coupon/
Authorization: Basic ZGVrbzpkZWtvMTIzQDEyMw==
Content-Type: application/json

{
    "coupon_code": "Deko10",
    "cart_total": 1692000,
    "ship_cost": 0,
    "cart_items": [
        {
            "id": 8,
            "quantity": 9,
            "name": "Sharafi Indian Hand Knotted",
            "total": 972000
        },
        {
            "id": 9,
            "quantity": 2,
            "name": "Indian Hand Knotted",
            "total": 720000
        }
    ],
    "user": 19
}


###
POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/order/
Authorization: Basic ZGVrb2J1ZGR5OkFkbWluYW51c2hhQDEyMw==
Content-Type: application/json

{
    "cartItems": [
        {
            "id": 145,
            "quantity": 1,
            "total_amount": "1080000",
            "free_product": "False"
        }
    ],
    "shipping_info": {
        "first_name": "deko",
        "address_1": "4rewrt6546",
        "city": "hjhgjh",
        "postcode": "876654",
        "Country_Region": "uiyiujhh",
        "state_country": "hgjghjghj",
        "email": "arun@zinavo.in",
        "phone": "9989875643",
        "alternative_phone": "alternative_phone"
    },
    "billing_info": {
        "first_name": "deko",
        "address_1": "4rewrt6546",
        "city": "hjhgjh",
        "postcode": "876654",
        "Country_Region": "uiyiujhh",
        "state_country": "hgjghjghj",
        "email": "arun@zinavo.in",
        "phone": "9989875643",
        "alternative_phone": "alternative_phone"
    },
    "total_amount": "108000.00",
    "tax_amount": "0.00",
    "amount": "97210.00",
    "shipping_cost": "0.00",
}







