POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/login/
Authorization: Basic ZGVrbzoxMjM0
Content-Type: application/json

{
    "username":"Arun",
    "password":"Arun@1234",
    }


###

GET http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/api/wishlist/15/
Authorization: Basic ZGVrbzoxMjM0



###
POST http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/cart/add-to-cart/1797/
Content-Type: application/json

{
    "review":"nice product",
    "rating":5,
    "product_id":1740,
    "user_id":15
}


### 
GET http://localhost:3000/api/products/



