import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import './app.scss';
import 'swiper/css';
import 'swiper/css/navigation';


import { Barlow } from 'next/font/google';
import ReduxProvider from "./redux/provider";
import { SessionProvider } from "next-auth/react";

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
});


export const metadata: Metadata = {
  title: "Deko Buddy",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <link
        rel="preload"
        href="http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/media/Main_banners/banner_1.webp"
        as="image"
        type="image/webp"
      />
      <link
        rel="preload"
        href="http://ec2-13-201-230-68.ap-south-1.compute.amazonaws.com:8002/media/Main_banners/banner_6.webp"
        as="image"
        type="image/webp"
      />
      <body className={barlow.className}>
        <ReduxProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
